// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/todos.ts";
import * as $3 from "./routes/api/todos/[id].ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/todos/index.tsx";
import * as $$0 from "./islands/todo-list.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/todos.ts": $2,
    "./routes/api/todos/[id].ts": $3,
    "./routes/index.tsx": $4,
    "./routes/todos/index.tsx": $5,
  },
  islands: {
    "./islands/todo-list.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
